name: Enes Kemal Ergin
author: Enes Kemal Ergin
title: Enes Kemal Ergin's Blog
description: Python | Bioinformatics | Big Data | Machine Learning
keywords: blog programming student resume technology presentations
tagline: Python and Data Science come together for Biology
logo: /images/me.jpg

url:

paginate: 5
paginate_path: "blog/page:num"

markdown: redcarpet
highlighter: pygments
permalink: pretty

exclude: ["CNAME", "README.md", "Gemfile", "Gemfile.lock", "LICENSE"]

disqus: eneskemalergin
analytics: UA-61953718-1
